In [1]:
import os
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import cv2
import random

# data 경로 설정
categories = ['train', 'test', 'val', 'auto_test'] # 전처리된 데이터셋을 훈련용, 평가용, 검증용으로 구분
data_dir = '/Users/igyuwon/data/osteoarthritis/'

In [2]:
def resize_image(img,size=(128,128)):
    return cv2.resize(img,size)

def he_img(img):
    return cv2.equalizeHist(img)

def clahe_image(img):
    clahe = cv2.createCLAHE(clipLimit=2.,tileGridSize=(8,8))
    cl_img = clahe.apply(img)
    return cl_img

def denoise_img(img):
    return cv2.fastNlMeansDenoising(img,None,30,7,21)

def normalize_img(img):
    return cv2.normalize(img,None,0,255,cv2.NORM_MINMAX)

def detect_edge(img):
    return cv2.Canny(img,100,200)

def blur_img(img):
    return cv2.GaussianBlur(img,(5,5),0)

def find_contour(img):
    ret, thresh = cv2.threshold(img, 127, 255, 0)
    contours, hiearchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    return contours

In [3]:
def load_data(data_dir):
    images = []
    for img_name in os.listdir(data_dir):
        img_path = os.path.join(data_dir, img_name)
        if os.path.isfile(img_path):  # 파일인지 확인
            img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            if img is not None:  # 이미지가 정상적으로 로드되었는지 확인
                img = resize_image(img)
                img = clahe_image(img)
                img = normalize_img(img)
                images.append(img)
    prepared_data = np.array(images)
    return prepared_data


In [4]:
all_data = {}

# 각 카테고리와 라벨에 따라 이미지를 처리
for category in categories:
    category_path = os.path.join(data_dir, category)
    all_data[category] = {}
    for label in range(5):
        label_path = os.path.join(category_path, str(label))
        if os.path.isdir(label_path):  # 라벨 경로가 디렉토리인지 확인
            print(f"카테고리: {category}, 라벨: {label} 처리 중....")
            processed_img_list = load_data(label_path)
            all_data[category][label] = processed_img_list
            print(f"처리된 이미지 수: {len(processed_img_list)}")
            print('='*40)

카테고리: train, 라벨: 0 처리 중....
처리된 이미지 수: 2286
카테고리: train, 라벨: 1 처리 중....
처리된 이미지 수: 1046
카테고리: train, 라벨: 2 처리 중....
처리된 이미지 수: 1516
카테고리: train, 라벨: 3 처리 중....
처리된 이미지 수: 757
카테고리: train, 라벨: 4 처리 중....
처리된 이미지 수: 173
카테고리: test, 라벨: 0 처리 중....
처리된 이미지 수: 639
카테고리: test, 라벨: 1 처리 중....
처리된 이미지 수: 296
카테고리: test, 라벨: 2 처리 중....
처리된 이미지 수: 447
카테고리: test, 라벨: 3 처리 중....
처리된 이미지 수: 223
카테고리: test, 라벨: 4 처리 중....
처리된 이미지 수: 51
카테고리: val, 라벨: 0 처리 중....
처리된 이미지 수: 328
카테고리: val, 라벨: 1 처리 중....
처리된 이미지 수: 153
카테고리: val, 라벨: 2 처리 중....
처리된 이미지 수: 212
카테고리: val, 라벨: 3 처리 중....
처리된 이미지 수: 106
카테고리: val, 라벨: 4 처리 중....
처리된 이미지 수: 27
카테고리: auto_test, 라벨: 0 처리 중....
처리된 이미지 수: 604
카테고리: auto_test, 라벨: 1 처리 중....
처리된 이미지 수: 275
카테고리: auto_test, 라벨: 2 처리 중....
처리된 이미지 수: 403
카테고리: auto_test, 라벨: 3 처리 중....
처리된 이미지 수: 200
카테고리: auto_test, 라벨: 4 처리 중....
처리된 이미지 수: 44


In [5]:
print(processed_img_list[0])

[[ 51  60  65 ...  99 105  93]
 [ 49  57  67 ... 102 102  93]
 [ 49  54  62 ... 105 102  89]
 ...
 [ 97 130 153 ...  31  15   3]
 [ 97 130 153 ...  34  22   6]
 [ 97 126 153 ...  28  19   3]]
