### Python 복습

### Markdown 수식 작성
    - LaTEX 태그로 작성 가능
$$
    \begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    \end{pmatrix}
    +
        \begin{pmatrix}
    5 & 5 & 5 \\
    5 & 5 & 5 \\
    \end{pmatrix}
$$
$$

    \begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    \end{pmatrix}
    \times
        \begin{pmatrix}
    5 & 5 \\
    5 & 5 \\
    5 & 5 \\
    \end{pmatrix}
$$

### Numpy
    - 데이터는 행렬로 표현(영상도 포함)
    - 선형대수 / 통계 연산을 위한 라이브러리

    Pandas : 데이터 분석에 가장 많이 활용
    Numpy : 알고리즘 활용에 numpy가 필수적 패키지

In [1]:
# 호출
import numpy as np

### array broadcasting
    - 차원이 다른 연산을 동일한 차원으로 자동으로 변경시켜 연산을 가능하게 해주는 것
    - 딥러닝에서 bias(편향) 계산을 할 때 주로 사용

In [6]:
# ary = np.array(np.random.randint(10, 100, 10))

# 초기 가중치 생성
ary = np.array(np.random.randn(10))# 표준 정규분포를 따르는 난수 생성 -> 초기 가중치 생성 때 사용
ary

array([ 1.45270874, -0.06938953,  0.52656408, -1.17043445,  0.75590862,
       -0.10483612, -0.62540367,  0.62424856, -0.87301775, -0.14663502])

In [7]:
# 편향값 생성
bias = np.random.rand(1)
bias

array([0.42859403])

In [8]:
ary + bias # array broadcasting

array([ 1.88130278,  0.3592045 ,  0.95515812, -0.74184041,  1.18450266,
        0.32375792, -0.19680963,  1.05284259, -0.44442371,  0.28195901])

### 통계함수
    - max, min, mean, median, var, std

In [10]:
np.max(ary),np.min(ary) # min-max normalization 때 사용 -> 데이터 정규화

(1.4527087428608558, -1.1704344459533744)

### Random 모듈
- seed : 랜덤 모듈의 규칙값. 난수 생성 환경 고정
- randint : 균등분포로 정수 생성
- randn : 정규분포로 난수 생성
- shuffle : 무작위 섞기
- choice : 특정확률로 데이터 뽑기

### seed

In [12]:
seed = 603 # 머신러닝, 딥러닝에서 하이퍼파라미터로 사용

np.random.seed(seed)
r1 = np.random.rand(10)

np.random.seed(1)
r2 = np.random.rand(10)

np.random.seed(seed)
r3 = np.random.rand(10)

In [13]:
r1,r2,r3

(array([0.06450168, 0.13338277, 0.10931622, 0.97127506, 0.85101842,
        0.96534748, 0.99727133, 0.93093441, 0.48533923, 0.63427833]),
 array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
        3.96767474e-01, 5.38816734e-01]),
 array([0.06450168, 0.13338277, 0.10931622, 0.97127506, 0.85101842,
        0.96534748, 0.99727133, 0.93093441, 0.48533923, 0.63427833]))

### &#8251; 머신러닝 예시
- scaling 처리 후 return 값으로 ndarray 타입 데이터로 출력

In [16]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

X = np.random.randint(1,100,10).reshape(-1,2) # 5행 2열
df = pd.DataFrame(X)
df

0   1
0  26  43
1  97  45
2  88  91
3  20  17
4  64  99

In [17]:
scaled_data = MinMaxScaler().fit_transform(df) # 데이터가 전체에서 어디에 있는지 백분위로 나타냄
scaled_data, type(scaled_data)

(array([[0.07792208, 0.31707317],
        [1.        , 0.34146341],
        [0.88311688, 0.90243902],
        [0.        , 0.        ],
        [0.57142857, 1.        ]]),
 numpy.ndarray)

### &#8251; 머신러닝 예시
- 초기값을 임의로 생성하여 zero 생성하여 대입할 때 다음과 같은 행렬을 작성하시오
$$
    \begin{pmatrix}
    난수 & 0 & 0 & 0\\
    0 & 난수 & 0 & 0\\
    0 & 0 & 난수 & 0\\
    0 & 0 & 0 & 난수\\
    \end{pmatrix}
$$

In [18]:
zero_ary = np.zeros((4,4))
zero_ary

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
w = np.random.randn(4)
shp = np.zeros((4,4))

for i in range(shp.shape[0]):
    for j in range(shp.shape[1]):
        if i == j: shp[i][j] = w[i]
        
shp

array([[ 0.62635569,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.02843835,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.03327178,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.45200419]])

In [46]:
diag_matrix = np.diag(np.random.rand(4))
diag_matrix

array([[0.52437397, 0.        , 0.        , 0.        ],
       [0.        , 0.5471456 , 0.        , 0.        ],
       [0.        , 0.        , 0.86930607, 0.        ],
       [0.        , 0.        , 0.        , 0.76344344]])

### Funtion
- 반복성을 줄이고 함수로 선언한 연산을 재사용
- 객체지향언어의 가장 큰 장점

```python
def 함수명(파라미터):
    return 출력값
```

In [51]:
# 리턴을 선언하지 않고 사용하는 경우 -> 함수가 연산 도구로만 사용될 때
# 전역변수, 지역변수
num = 603
print(num)

def today():
    num = 604
    print(num)
    
today()
print('='*10)
print(num)

603
604
603


In [52]:
num = 603
print(num)

def today():
    global num
    num = 604
    print(num)
    
today()
print('='*10)
print(num)

603
604
604


### map 함수와 pandas apply는 유사한 기능
- 순서가 있는 데이터값에 함수를 모두 적용하여 결과를 출력하는 함수

```python
map(적용할 함수, 입력할 데이터)
```

In [55]:
num_txt = '1 2 3 4 5 6'
num_int = list(map(int,num_txt.split(" ")))

num_int

[1, 2, 3, 4, 5, 6]

### lambda 함수
- 간단한 연산을 구현하여 일시적으로 사용하는 함수

```python
lambda 리턴: 연산
```

In [58]:
seq = np.random.randint(1,101,10)
q = list(map(lambda x: x//3, seq))

seq, q

(array([33, 97, 71, 25, 76, 38, 83, 78, 22, 39]),
 [11, 32, 23, 8, 25, 12, 27, 26, 7, 13])